[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
remappings = [
	"openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
	"openzeppelin-contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/",
	"@openzeppelin/contracts/=lib/openzeppelin-contracts-upgradeable/lib/openzeppelin-contracts/contracts/",
	"@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/"
]

fs_permissions = [
	{ access = "read", path = "./" },
	{ access = "write", path = "./deployments" }
]
default_rpc_url = "http://127.0.0.1:8545"

[profile.mumbai]
rpc_url = "${MUMBAI_RPC_URL}"
chain_id = 80001

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
